/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    AIconCopy: typeof import('@arco-design/web-vue')['IconCopy']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AInputGroup: typeof import('@arco-design/web-vue')['InputGroup']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AOption: typeof import('@arco-design/web-vue')['Option']
    APageHeader: typeof import('@arco-design/web-vue')['PageHeader']
    ARow: typeof import('@arco-design/web-vue')['Row']
    AScroll: typeof import('@arco-design/web-vue')['Scroll']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATypography: typeof import('@arco-design/web-vue')['Typography']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    ExpandedContent: typeof import('./src/components/ResultTable/ExpandedContent.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    ResultOperation: typeof import('./src/components/ResultTable/ResultOperation.vue')['default']
    ResultTable: typeof import('./src/components/ResultTable/ResultTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
  }
}
